//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisory_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bien
    {
        public int id { get; set; }
        public int type_bien_id { get; set; }
        public string libelle { get; set; }
        public string code { get; set; }
        public string prix_unitaire { get; set; }
        public Nullable<int> nbr_places_dispo { get; set; }
        public Nullable<int> nbr_places_total { get; set; }
    
        public virtual TypeBien TypeBien { get; set; }
    }
}
