//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAdvisory_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripAdvisorEntities : DbContext
    {
        public TripAdvisorEntities()
            : base("name=TripAdvisorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bien> Biens { get; set; }
        public virtual DbSet<TypeBien> TypeBiens { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
    }
}
